### ISSUE TITLE
prevent systemd predictable network names, use script name in eth0

### ISSUE THREAD

**Issue by xmw** [leahneukirchen/ignite#19]
Plain archlinux + packer + ignite-git installation has no left-over /etc/udev/rules.d/70-persistent-net.rules and >udev-201 starts renaming the links to enp2s8.

/etc/sv/eth0 has to be edited and renamed to make this work.

TODO: revert that behaviour to old style. I look into [1].

[1] http://us.generation-nt.com/answer/gentoo-dev-call-testers-udev-predictable-network-interface-names-help-210046042.html

**Comment by xmw** [comment]
ln -s /dev/null /etc/udev/rules.d/80-net-name-slot.rules
[1] http://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames

**Comment by leahneukirchen** [comment]
Michael Weber notifications@github.com writes:

> ln -s /dev/null /etc/udev/rules.d/80-net-name-slot.rules
> [1]
> http://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames

Mentioned in README.

## 

Christian Neukirchen  chneukirchen@gmail.com  http://chneukirchen.org
