### ISSUE TITLE
provide rc.conf template / install README file

### ISSUE THREAD

**Issue by xmw** [leahneukirchen/ignite#20]
non-migrated systems lack rc.conf, and retrieving the README file from packer-tmp/website sucks.

Please install README to /usr/share/doc/... and backup+install /etc/rc.conf

**Comment by leahneukirchen** [comment]
Updated ignite-git PKGBUILD to do that.

Problem is that /etc/rc.conf is owned by initscripts (which is not being
distributed anymore, but still installed on some machines).

Putting both to /usr/share/doc/ignite.
